###############################################################################
#  Symbolic Finite Tree Automata Library
#
#  Copyright (c) 2010  Ondra Lengal <ondra@lengal.net>
#
#  Description:
#    SFTA intersection test.
#
###############################################################################

set test "intersection test"
send "sfta -i d d\n"
expect {
    -re "Version:.*"	{ pass "intersection test" }
}
